Repository PyThaiNLP/pythainlp, pull requests merged in 2019-10, with the labels that each got.

#281 Use artagger from main repo, use tensorflow < 2
  README.md
  appveyor.yml
  docs/clean_directory.sh
  docs/notes/command_line.rst
  docs/notes/installation.rst
  pythainlp/tokenize/__init__.py
  pythainlp/transliterate/ipa.py
  pythainlp/transliterate/thai2rom.py
  pythainlp/ulmfit/__init__.py
  setup.py
Labels: refactoring

#278 Remove racing condition in making pythainlp data directory
  pythainlp/tools/__init__.py
Labels: bug

#280 Optimize keyboard layout switching translation code & digits translation
  pythainlp/util/digitconv.py
  pythainlp/util/keyboard.py
Labels: refactoring

#279 pythainlp.spell: Fix type annotations, docstring spellings, etc.
  pythainlp/spell/__init__.py
  pythainlp/spell/pn.py
  tests/test_spell.py
Labels: bug, documentation

#283 Remove deepcut, keras, tensorflow from dependencies
  .travis.yml
  README.md
  appveyor.docs.yml
  appveyor.yml
  pythainlp/tokenize/deepcut.py
  setup.py
Labels: refactoring

#292 Minimum possible version requirement
  requirements.txt
  setup.py
Labels: refactoring

#294 Added docs on PYTHAINLP_DATA_DIR environ variable
  docs/notes/installation.rst
  pythainlp/tools/__init__.py
Labels: documentation

#295 Refactor util package as well as improve performance
  docs/api/util.rst
  pythainlp/util/__init__.py
  pythainlp/util/normalize.py
  pythainlp/util/numtoword.py
  pythainlp/util/thaiwordcheck.py
  tests/test_util.py
Labels: refactoring

#297 [Corpus] Include Thai person names directly into the package
  pythainlp/corpus/common.py
  pythainlp/corpus/family_names_th.txt
  pythainlp/corpus/person_names_female_th.txt
  pythainlp/corpus/person_names_male_th.txt
  setup.py
Labels: corpus

#296 Upgrade AppVeyor and Travis build files
  .travis.yml
  README.md
  appveyor.docs.yml
  appveyor.yml
  docs/build_docs.sh
  docs/clean_directory.sh
  docs/conf.py
  docs/notes/getting_started.rst
  pythainlp/__init__.py
  pythainlp/corpus/__init__.py
  setup.py
  tests/test_benchmarks.py
  tests/test_corpus.py
  tests/test_soundex.py
  tests/test_spell.py
  tests/test_summarize.py
  tests/test_tag.py
  tests/test_tokenize.py
  tests/test_tools.py
  tests/test_transliterate.py
  tests/test_ulmfit.py
  tests/test_util.py
  tests/test_word_vector.py
Labels: refactoring

#303 Add pythainlp.util.thai_time
  appveyor.yml
  docs/api/util.rst
  pythainlp/util/__init__.py
  pythainlp/util/date.py
  pythainlp/util/thai_time.py
  pythainlp/util/thaiwordcheck.py
  tests/test_util.py
Labels: enhancement

#307 Remove some words from dictionary
  pythainlp/corpus/words_th.txt
Labels: corpus

#309 Update tokenizers and test cases
  pythainlp/tokenize/longest.py
  pythainlp/tokenize/multi_cut.py
  pythainlp/tokenize/ssg.py
  tests/test_tokenize.py
Labels: refactoring
