Repository PyThaiNLP/pythainlp, pull requests merged in 2019-08, with the labels that each got.

#244 Include case THANTHAKHAT and SARA U, UU too
  pythainlp/util/normalize.py
Labels: bug

#243 Merge document from 2.0 to dev
  docs/api/corpus.rst
  docs/api/soundex.rst
  docs/api/spell.rst
  docs/api/tag.rst
  docs/api/tokenize.rst
  docs/api/transliterate.rst
  docs/api/word_vector.rst
  docs/conf.py
  pythainlp/corpus/__init__.py
  pythainlp/corpus/common.py
  pythainlp/corpus/conceptnet.py
  pythainlp/corpus/tnc.py
  pythainlp/corpus/wordnet.py
  pythainlp/soundex/__init__.py
  pythainlp/soundex/lk82.py
  pythainlp/soundex/metasound.py
  pythainlp/soundex/udom83.py
  pythainlp/spell/__init__.py
  pythainlp/spell/pn.py
  pythainlp/summarize/__init__.py
  pythainlp/tag/__init__.py
  pythainlp/tag/locations.py
  pythainlp/tag/named_entity.py
  pythainlp/tokenize/__init__.py
  pythainlp/tokenize/deepcut.py
  pythainlp/tokenize/etcc.py
  pythainlp/tokenize/longest.py
  pythainlp/tokenize/multi_cut.py
  pythainlp/tokenize/newmm.py
  pythainlp/tokenize/pyicu.py
  pythainlp/tokenize/tcc.py
  pythainlp/tools/__init__.py
  pythainlp/transliterate/__init__.py
  pythainlp/ulmfit/__init__.py
  pythainlp/util/collate.py
  pythainlp/util/date.py
  pythainlp/util/digitconv.py
  pythainlp/util/keyboard.py
  pythainlp/util/keywords.py
  pythainlp/util/normalize.py
  pythainlp/util/numtoword.py
  pythainlp/util/thai.py
  pythainlp/util/thaiwordcheck.py
  pythainlp/util/wordtonum.py
  pythainlp/word_vector/__init__.py
Labels: documentation

#248 Add tokenization-benchmark to PyThaiNLP
  bin/word-tokenization-benchmark
  docs/api/benchmarks.rst
  pythainlp/__init__.py
  pythainlp/benchmarks/__init__.py
  pythainlp/benchmarks/word_tokenisation.py
  setup.py
  tests/data/sentences.yml
  tests/test_benchmarks.py
Labels: benchmark
