Repository PyThaiNLP/pythainlp, pull requests merged in 2020-08, with the labels that each got.

#459 fix crfcut last segment not included if not predicted as end-of-sentence
  pythainlp/tokenize/crfcut.py
  tests/test_tokenize.py
Labels: bug

#466 provinces(): Fix type hinting, clean code, remove thailand_provinces_th.txt
  pythainlp/corpus/common.py
  pythainlp/corpus/core.py
  pythainlp/corpus/thailand_provinces_th.txt
  tests/test_corpus.py
Labels: enhancement

#472 Fix typo in README.md
  README.md
Labels: documentation
