Repository PyThaiNLP/pythainlp, pull requests merged in 2020-06, with the labels that each got.

#421 Update check corpus version
  pythainlp/cli/data.py
  pythainlp/corpus/__init__.py
  pythainlp/corpus/core.py
  pythainlp/tag/named_entity.py
  tests/test_corpus.py
  tests/test_util.py
Labels: bug, corpus

#438 Add dict and other iterables support for custom_dict input
  pythainlp/spell/pn.py
  tests/test_spell.py
Labels: enhancement

#442 Fix update bug
  README.md
  pythainlp/__init__.py
  pythainlp/corpus/core.py
  setup.cfg
  setup.py
Labels: bug
