Repository PyThaiNLP/pythainlp, pull requests merged in 2020-05, with the labels that each got.

#379 Move non-init code out of __init__.py files
  README.md
  docs/api/tokenize.rst
  docs/api/util.rst
  pythainlp/__init__.py
  pythainlp/__main__.py
  pythainlp/benchmarks/__init__.py
  pythainlp/corpus/__init__.py
  pythainlp/corpus/common.py
  pythainlp/corpus/core.py
  pythainlp/corpus/tnc.py
  pythainlp/corpus/ttc.py
  pythainlp/soundex/__init__.py
  pythainlp/soundex/core.py
  pythainlp/spell/__init__.py
  pythainlp/spell/core.py
  pythainlp/spell/pn.py
  pythainlp/summarize/__init__.py
  pythainlp/summarize/core.py
  pythainlp/tag/__init__.py
  pythainlp/tag/named_entity.py
  pythainlp/tokenize/__init__.py
  pythainlp/tokenize/core.py
  pythainlp/tokenize/crfcut.py
  pythainlp/tokenize/deepcut.py
  pythainlp/tokenize/etcc.py
  pythainlp/tokenize/longest.py
  pythainlp/tokenize/multi_cut.py
  pythainlp/tokenize/newmm.py
  pythainlp/tokenize/tcc.py
  pythainlp/tokenize/trie.py
  pythainlp/transliterate/__init__.py
  pythainlp/transliterate/core.py
  pythainlp/transliterate/thai2rom.py
  pythainlp/transliterate/thaig2p.py
  pythainlp/ulmfit/__init__.py
  pythainlp/util/__init__.py
  pythainlp/util/date.py
  pythainlp/util/numtoword.py
  pythainlp/util/trie.py
  pythainlp/word_vector/__init__.py
  tests/test_summarize.py
  tests/test_tokenize.py
  tests/test_ulmfit.py
  tests/test_util.py
  travis_pypi_setup.py
Labels: refactoring

#354 Verb-like commands for "thainlp" command-line program
  docs/notes/command_line.rst
  docs/notes/installation.rst
  pythainlp/__main__.py
  pythainlp/cli/__init__.py
  pythainlp/cli/corpus.py
  pythainlp/cli/data.py
  pythainlp/cli/soundex.py
  pythainlp/cli/tag.py
  pythainlp/cli/tokenize.py
  pythainlp/corpus/__init__.py
  pythainlp/corpus/core.py
  tests/test_corpus.py
Labels: enhancement

#383 Fix "thainlp tokenize sent" command line
  docs/notes/command_line.rst
  pythainlp/cli/tokenize.py
Labels: bug

#382 Refactor Trie __init__, reduce complexity
  pythainlp/util/trie.py
  tests/test_util.py
Labels: refactoring

#389 Fixing and enhancing text normalization funcitons
  docs/api/util.rst
  pythainlp/util/__init__.py
  pythainlp/util/normalize.py
  tests/test_util.py
Labels: bug

#393 Add test case for deprecated delete_tone()
  pythainlp/util/normalize.py
  tests/test_util.py
Labels: documentation

#395 Use raw string for regex
  pythainlp/benchmarks/word_tokenization.py
Labels: bug

#396 Refactor NorvigSpellChecker class
  pythainlp/spell/pn.py
  tests/test_spell.py
Labels: refactoring

#397 Split ulmfit and word_vector huge __init__.py into smaller files
  docs/api/ulmfit.rst
  docs/api/util.rst
  docs/api/word_vector.rst
  pythainlp/tokenize/__init__.py
  pythainlp/ulmfit/__init__.py
  pythainlp/ulmfit/core.py
  pythainlp/ulmfit/preprocess.py
  pythainlp/ulmfit/tokenizer.py
  pythainlp/util/__init__.py
  pythainlp/util/normalize.py
  pythainlp/word_vector/__init__.py
  pythainlp/word_vector/core.py
  tests/test_ulmfit.py
Labels: refactoring

#399 Make countthai() to cover a case that the text has only ignore_chars
  pythainlp/util/thai.py
  tests/test_util.py
Labels: bug

#401 Rewrite Unigram pos_tag
  pythainlp/corpus/ud_thai_pud_unigram_tagger.dill
  pythainlp/corpus/ud_thai_pud_unigram_tagger.json
  pythainlp/tag/orchid.py
  pythainlp/tag/orchid_preprocessing.py
  pythainlp/tag/perceptron.py
  pythainlp/tag/unigram.py
  setup.py
Labels: refactoring

#403 Remove NLTK from mandatory dependency
  README.md
  docs/api/corpus.rst
  pythainlp/corpus/wordnet.py
  requirements.txt
  setup.py
Labels: refactoring

#369 [WIP] Fix tokenization benchmark statistics
  bin/word-tokenization-benchmark
  pythainlp/benchmarks/word_tokenization.py
Labels: benchmark

#409 Remove tqdm from base requirements
  pythainlp/benchmarks/word_tokenization.py
  pythainlp/corpus/__init__.py
  pythainlp/corpus/core.py
  pythainlp/soundex/core.py
  pythainlp/tag/named_entity.py
  pythainlp/tools/__init__.py
  pythainlp/tools/path.py
  pythainlp/transliterate/core.py
  pythainlp/word_vector/core.py
  requirements.txt
  setup.py
  tests/test_benchmarks.py
  tests/test_corpus.py
  tests/test_soundex.py
  tests/test_tools.py
  tests/test_transliterate.py
  tests/test_word_vector.py
Labels: refactoring

#412 More test cases for tag.pos_tag and util.date, util.time, util.wordtonum
  CONTRIBUTING.md
  README.md
  appveyor.docs.yml
  appveyor.yml
  docs/api/benchmarks.rst
  docs/api/soundex.rst
  docs/api/tag.rst
  docs/api/util.rst
  docs/notes/installation.rst
  pythainlp/benchmarks/word_tokenization.py
  pythainlp/corpus/corpus_license.md
  pythainlp/corpus/words_th_thai2fit_201810.txt
  pythainlp/tag/named_entity.py
  pythainlp/transliterate/core.py
  pythainlp/util/__init__.py
  pythainlp/util/date.py
  pythainlp/util/normalize.py
  pythainlp/util/thaiwordcheck.py
  pythainlp/util/time.py
  pythainlp/util/trie.py
  pythainlp/util/wordtonum.py
  tests/data/sentences.yml
  tests/test_soundex.py
  tests/test_tag.py
  tests/test_tokenize.py
  tests/test_ulmfit.py
  tests/test_util.py
  tokenization-benchmark.md
Labels: refactoring

#413 Refactor thaiword_to_date() and return None if cannot convert
  pythainlp/soundex/lk82.py
  pythainlp/soundex/udom83.py
  pythainlp/transliterate/royin.py
  pythainlp/util/date.py
  tests/test_soundex.py
  tests/test_util.py
Labels: refactoring

#414 Properly check if download() is needed in get_corpus_path()
  README.md
  pythainlp/corpus/__init__.py
  pythainlp/corpus/core.py
  pythainlp/tag/named_entity.py
  pythainlp/tag/pos_tag.py
  pythainlp/tools/__init__.py
  pythainlp/tools/path.py
  pythainlp/transliterate/royin.py
  pythainlp/transliterate/thai2rom.py
  pythainlp/transliterate/thaig2p.py
  pythainlp/ulmfit/core.py
  pythainlp/word_vector/core.py
  tests/test_transliterate.py
Labels: refactoring

#416 Add more docs
  docs/api/corpus.rst
  docs/api/transliterate.rst
  docs/index.rst
  docs/notes/license.rst
  pythainlp/corpus/core.py
  pythainlp/tag/perceptron.py
  pythainlp/transliterate/royin.py
Labels: documentation

#420 Add coveralls to GitHub Actions
  .github/workflows/pythainlp-test.yml
  .travis.yml
Labels: enhancement

#418 Add unit test to CLI functions
  pythainlp/__main__.py
  pythainlp/cli/__init__.py
  pythainlp/cli/data.py
  pythainlp/cli/soundex.py
  pythainlp/cli/tag.py
  pythainlp/cli/tokenize.py
  pythainlp/corpus/corpus_license.md
  tests/__init__.py
  tests/test_cli.py
  tests/test_corpus.py
  tests/test_tokenize.py
  tests/test_tools.py
  tests/test_util.py
Labels: bug, refactoring
