Repository PyThaiNLP/pythainlp, pull requests merged in 2020-12, with the labels that each got.

#492 Update tag.rst
  docs/api/tag.rst
Labels: documentation

#493 Pin h5py to < 3 to avoid breaks in Keras in Tensorflow 2.3.1 + Update test config
  .github/workflows/pythainlp-test.yml
  .travis.yml.old
  appveyor.docs.yml
  appveyor.yml
  requirements.txt
Labels: refactoring

#490 thai_strftime: Normalize output for unsupported directive
  pythainlp/util/strftime.py
Labels: bug

#494 Add issue/PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue_report.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/pythainlp-test.yml
Labels: refactoring

#497 Remove unused CI configuration files
  .circleci/config.yml
  .travis.yml.old
  README.md
  tox.ini
  travis_pypi_setup.py
Labels: refactoring

#484 Add model option to attacut.tokenize()
  pythainlp/tokenize/attacut.py
Labels: documentation, enhancement, hacktoberfest-accepted

#505 Add check versions for pythainlp.corpus
  pythainlp/corpus/__init__.py
  pythainlp/corpus/core.py
  tests/test_corpus.py
Labels: enhancement

#503 Add NERCut tokenization engine
  docs/api/tokenize.rst
  pythainlp/tokenize/core.py
  pythainlp/tokenize/nercut.py
  tests/test_tokenize.py
Labels: enhancement

#502 Add create_wordlist
  docs/api/corpus.rst
  docs/api/summarize.rst
  docs/api/tag.rst
  pythainlp/corpus/__init__.py
  pythainlp/corpus/common.py
  pythainlp/corpus/util.py
  pythainlp/util/__init__.py
  tests/test_corpus.py
Labels: enhancement

#439 Add pythainlp.translate
  .github/workflows/test.yml
  appveyor.yml
  docs/api/translate.rst
  pythainlp/corpus/core.py
  pythainlp/translate/__init__.py
  pythainlp/translate/core.py
  setup.py
  tests/test_translate.py
Labels: enhancement, hacktoberfest-accepted
