Repository PyThaiNLP/pythainlp, pull requests merged in 2021-06, with the labels that each got.

#573 Use get_vector() instead of deprecated word_vec()
  pythainlp/word_vector/core.py
Labels: refactoring

#568 Manually merge update-royin branch with dev branch to add O-ANG rule
  .github/workflows/macos-test.yml
  pythainlp/corpus/words_th.txt
  pythainlp/tokenize/multi_cut.py
  pythainlp/tokenize/newmm.py
  pythainlp/transliterate/royin.py
  tests/test_tokenize.py
Labels: enhancement

#576 Add get_corpus_default_db and thainer 1.5 model
  docs/api/corpus.rst
  pythainlp/corpus/__init__.py
  pythainlp/corpus/core.py
  pythainlp/corpus/default_db.json
  pythainlp/corpus/thainer_crf_1_5.model
  tests/test_corpus.py
Labels: corpus

#585 Fix token_max_len bug that makes it always zero
  pythainlp/tokenize/newmm.py
Labels: bug
