Repository PyThaiNLP/pythainlp, pull requests merged in 2022-10, with the labels that each got.

#723 Fix/broken numeric data format (#652)
  pythainlp/tokenize/_utils.py
  pythainlp/tokenize/core.py
  tests/test_tokenize.py
Labels: bug

#735 Feature/integrate transliteration dictionary (#681)
  pythainlp/corpus/th_en_translit.py
  pythainlp/corpus/th_en_transliteration_v1.4.tsv
  pythainlp/transliterate/core.py
  pythainlp/transliterate/lookup.py
  tests/test_transliterate.py
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#728 Delete all LST20 model
  docs/api/tokenize.rst
  docs/api/wangchanberta.rst
  pythainlp/augment/wordnet.py
  pythainlp/tag/lst20.py
  pythainlp/tag/lst20_ner_onnx.py
  pythainlp/tag/named_entity.py
  pythainlp/tag/perceptron.py
  pythainlp/tag/pos_tag.py
  pythainlp/tag/thainer.py
  pythainlp/tag/unigram.py
  pythainlp/tokenize/__init__.py
  pythainlp/tokenize/core.py
  pythainlp/tokenize/crfcls.py
  pythainlp/wangchanberta/__init__.py
  pythainlp/wangchanberta/core.py
  pythainlp/wangchanberta/postag.py
  tests/test_tag.py
  tests/test_tokenize.py
  tests/test_wangchanberta.py
Labels: corpus

#742 Add style.css: extend docs page width
  .gitignore
  docs/_static/style.css
  docs/conf.py
Labels: documentation, hacktoberfest-accepted

#743 Add Thai2Rom ONNX model
  notebooks/convert_thai2rom_to_onnx.ipynb
  pythainlp/corpus/default_db.json
  pythainlp/corpus/thai2rom_decoder.onnx
  pythainlp/corpus/thai2rom_encoder.onnx
  pythainlp/corpus/thai2rom_loader_onnx.json
  pythainlp/transliterate/core.py
  pythainlp/transliterate/thai2rom.py
  pythainlp/transliterate/thai2rom_onnx.py
  tests/test_transliterate.py
Labels: corpus, refactoring, hacktoberfest-accepted, dependencies

#751 Feature: keyword extraction with keybert and frequency ranking
  docs/api/summarize.rst
  pythainlp/summarize/__init__.py
  pythainlp/summarize/core.py
  pythainlp/summarize/keybert.py
  tests/test_summarize.py
Labels: enhancement, hacktoberfest-accepted
