Repository PyThaiNLP/pythainlp, pull requests merged in 2023-10, with the labels that each got.

#844 Add extra segmentation style for `paragraph_tokenize` function
  pythainlp/tokenize/core.py
  pythainlp/tokenize/wtsplit.py
Labels: Hacktoberfest, hacktoberfest-accepted

#850 Improving the documentation byt fixing the typos, adding necesarry details and explanation of the code and the missing necessary details about model and example.
  docs/api/augment.rst
  docs/api/benchmarks.rst
  docs/api/coref.rst
  docs/api/corpus.rst
  docs/api/el.rst
  docs/api/generate.rst
  docs/api/khavee.rst
  docs/api/parse.rst
  docs/api/soundex.rst
  docs/api/spell.rst
  docs/api/tokenize.rst
  docs/api/tools.rst
  docs/api/translate.rst
  docs/api/transliterate.rst
  docs/api/ulmfit.rst
  docs/api/util.rst
  docs/api/wangchanberta.rst
  docs/api/word_vector.rst
  docs/api/wsd.rst
Labels: documentation, hacktoberfest-accepted

#851 Fix ISO 11940 duplicate keys
  pythainlp/transliterate/iso_11940.py
  setup.cfg
Labels: bug, hacktoberfest-accepted

#849 Add pythainlp.util.rhyme
  docs/api/util.rst
  pythainlp/util/__init__.py
  pythainlp/util/pronounce.py
  tests/test_util.py
Labels: enhancement, hacktoberfest-accepted

#852 Fix duplicate key in IPA to RTGS phoneme mapping
  pythainlp/util/phoneme.py
Labels: bug, hacktoberfest-accepted
