Repository PyThaiNLP/pythainlp, pull requests merged in 2023-11, with the labels that each got.

#856 Improve: [newmm tokenizer] Change regular expression of "non-thai-characters"
  pythainlp/tokenize/newmm.py
  tests/test_tokenize.py
Labels: bug

#857 add function for pos tag with transformers
  pythainlp/tag/__init__.py
  pythainlp/tag/pos_tag.py
  tests/test_tag.py
Labels: enhancement

#862 Add: remove_repeat_consonants()
  pythainlp/util/__init__.py
  pythainlp/util/remove_trailing_repeat_consonants.py
  tests/test_util.py
Labels: enhancement

#865 Update `pos_tag_transformers` function
  pythainlp/tag/pos_tag.py
  tests/test_tag.py
Labels: documentation, refactoring
