Repository PyThaiNLP/pythainlp, pull requests merged in 2023-12, with the labels that each got.

#870 Add Volubilis corpus
  pythainlp/corpus/__init__.py
  pythainlp/corpus/corpus_license.md
  pythainlp/corpus/volubilis.py
  pythainlp/corpus/volubilis_modified.txt
  tests/test_corpus.py
Labels: enhancement, corpus

#878 Update Git Actions versions
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy_docs.yml
  .github/workflows/lint.yml
  .github/workflows/macos-test.yml
  .github/workflows/pypi-publish.yml
  .github/workflows/pypi-test.yml
  .github/workflows/test.yml
  .github/workflows/windows-test.yml
Labels: infrastructure

#880 Fix ruff args in workflow
  .github/workflows/lint.yml
Labels: infrastructure

#881 Revise ruff args in workflow
  .github/workflows/lint.yml
Labels: infrastructure

#879 Add Thai ICU wordbreak dictionary to PyThaiNLP corpus
  pythainlp/corpus/__init__.py
  pythainlp/corpus/core.py
  pythainlp/corpus/corpus_license.md
  pythainlp/corpus/icu.py
  pythainlp/corpus/icubrk_th.txt
  tests/test_corpus.py
Labels: enhancement, corpus

#886 Add license info to /tests and README_TH.md
  README_TH.md
  pythainlp/tag/pos_tag.py
  tests/__init__.py
  tests/test_ancient.py
  tests/test_augment.py
  tests/test_benchmarks.py
  tests/test_classify.py
  tests/test_cli.py
  tests/test_coref.py
  tests/test_corpus.py
  tests/test_el.py
  tests/test_generate.py
  tests/test_khavee.py
  tests/test_misspell.py
  tests/test_parse.py
  tests/test_soundex.py
  tests/test_spell.py
  tests/test_summarize.py
  tests/test_tag.py
  tests/test_tokenize.py
  tests/test_tools.py
  tests/test_util.py
  tests/test_wsd.py
Labels: documentation

#873 Add PhayaThaiBERT engine with new features [WIP]
  pythainlp/augment/lm/__init__.py
  pythainlp/augment/lm/phayathaibert.py
  pythainlp/phayathaibert/__init__.py
  pythainlp/phayathaibert/core.py
  pythainlp/tag/named_entity.py
  pythainlp/tag/pos_tag.py
  pythainlp/tokenize/core.py
  tests/test_augment.py
  tests/test_tokenize.py
Labels: enhancement

#889 phayathaibert, khavee, parse: Code clean up
  pythainlp/augment/lm/phayathaibert.py
  pythainlp/augment/lm/wangchanberta.py
  pythainlp/augment/wordnet.py
  pythainlp/khavee/__init__.py
  pythainlp/khavee/core.py
  pythainlp/khavee/example.py
  pythainlp/parse/__init__.py
  pythainlp/parse/core.py
  pythainlp/parse/spacy_thai_engine.py
  pythainlp/parse/transformers_ud.py
  pythainlp/parse/ud_goeswith.py
  pythainlp/phayathaibert/__init__.py
  pythainlp/phayathaibert/core.py
Labels: bug, refactoring

#890 Add pythainlp.corpus.find_synonyms
  docs/api/corpus.rst
  pythainlp/corpus/__init__.py
  pythainlp/corpus/common.py
  tests/test_corpus.py
Labels: enhancement

#892 ruff: docstring-code-format = true
  pyproject.toml
Labels: infrastructure
