Repository PyThaiNLP/pythainlp, pull requests merged in 2024-12, with the labels that each got.

#1028 Update warn_deprecation to get deprecated and removal versions
  pythainlp/cls/__init__.py
  pythainlp/corpus/common.py
  pythainlp/tools/core.py
  pythainlp/util/normalize.py
  pythainlp/util/thaiwordcheck.py
Labels: enhancement

#1027 PyThaiNLP v5.0.5
  CITATION.cff
  README.md
  README_TH.md
  pythainlp/__init__.py
  pythainlp/cls/__init__.py
  pythainlp/corpus/common.py
  pythainlp/phayathaibert/core.py
  pythainlp/tokenize/core.py
  pythainlp/tools/__init__.py
  pythainlp/tools/core.py
  pythainlp/util/__init__.py
  pythainlp/util/normalize.py
  pythainlp/util/thaiwordcheck.py
  pythainlp/wangchanberta/core.py
  setup.cfg
  setup.py
Labels: bug

#1029 Remove unnecessary enumerate in expand_maiyamok
  pythainlp/util/normalize.py
Labels: refactoring

#1031 Simplify calculate_f_year_f_dev()
  pythainlp/util/thai_lunar_date.py
Labels: refactoring

#1051 Add How to cut a new release doc
  CONTRIBUTING.md
  release.md
Labels: documentation
