Repository PyThaiNLP/pythainlp, pull requests merged in 2024-10, with the labels that each got.

#924 Add preprocess function to split whitespace before `romanize`
  pythainlp/transliterate/core.py
Labels: hacktoberfest-accepted

#926 Tone collate fixed
  pythainlp/util/collate.py
  tests/test_util.py
Labels: hacktoberfest-accepted

#929 test: Add more cases too covered all possible Marttra
  tests/test_khavee.py
Labels: hacktoberfest-accepted

#927 Added list of string support to sent_tokenize
  pythainlp/tokenize/core.py
  tests/test_tokenize.py
Labels: enhancement, hacktoberfest-accepted

#947 Upgrade Python in CI to 3.9
  .github/workflows/deploy-docs.yml
  .github/workflows/lint.yml
  .github/workflows/pypi-publish.yml
  .github/workflows/pypi-test.yml
  .github/workflows/unittest-macos.yml
  .github/workflows/unittest-windows.yml
  .github/workflows/unitttest-ubuntu.yml
  .python-version
  pyproject.toml
  pythainlp/util/date.py
  setup.py
  tests/test_ancient.py
  tests/test_augment.py
  tests/test_benchmarks.py
  tests/test_classify.py
  tests/test_coref.py
  tests/test_el.py
  tests/test_generate.py
  tests/test_khavee.py
  tests/test_misspell.py
  tests/test_morpheme.py
  tests/test_parse.py
  tests/test_soundex.py
  tests/test_summarize.py
  tests/test_translate.py
  tests/test_transliterate.py
  tests/test_ulmfit.py
  tests/test_util.py
  tests/test_wsd.py
  tox.ini
Labels: infrastructure

#949 Fix nltk.downloader warning
  .github/workflows/unittest-macos.yml
  .github/workflows/unittest-windows.yml
  .github/workflows/unitttest-ubuntu.yml
  README.md
  README_TH.md
Labels: infrastructure

#951 Unify unit test workflow across OSes
  .github/workflows/unittest-macos.yml
  .github/workflows/unittest.yml
  .github/workflows/unitttest-ubuntu.yml
Labels: infrastructure
